### ISSUE TITLE
[PE-D][Tester C] Confusing documentation on UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T12-1/tp#101]
![Screenshot 2024-04-05 at 5.43.56 PM.png](https://raw.githubusercontent.com/TimothyLKM/ped/main/files/e215d9ec-cf1b-484d-acc2-8c0ad765856c.png)

MMMM DD YYYY is confusing because it makes me think i can write a 4 letter month only?

maybe you could change it to  [name of the month]

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: TimothyLKM/ped#6

**Comment by BenjoBurger** [comment]
I have given examples below this line to avoid confusion. Also, I used this format as it is the standard date format that is used by Java. Do you feel using [name of the month] [day of the month] [year] would improve readability?

**Comment by BenjoBurger** [comment]
I have given examples below this line to avoid confusion. Also, I used this format as it is the standard date format that is used by Java. Do you feel using [name of the month] [day of the month] [year] would improve readability?
