### ISSUE TITLE
[PE-D][Tester B] FileNotFoundException upon running JAR file

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T12-1/tp#73]
![image.png](https://raw.githubusercontent.com/Kobot7/ped/main/files/75ab8704-523b-4b88-afad-df0b624e9dc0.png)

Upon running the jar file, FileNotFoundException error is printed. Application is still able to run afterwards. Unable to determine what functions will be affected by the lack of text file yet.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Kobot7/ped#1

**Comment by ningsongshen** [comment]
closed with scraper updates
