### ISSUE TITLE
[PE-D][Tester A] [UG] Not enough visuals e.g., screenshots/diagrams

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T12-1/tp#78]
Lack of visuals and diagrams in UG. There is no UML graph.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Andy123qq4/ped#3

**Comment by BenjoBurger** [comment]
I have added more visuals but i don't think there is a need for UML diagrams in the UG
