### ISSUE TITLE
[PE-D][Tester C] daily Function does not work properly

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T12-1/tp#97]
![Screenshot 2024-04-05 at 5.31.32 PM.png](https://raw.githubusercontent.com/TimothyLKM/ped/main/files/87592f97-9c79-47fb-9f34-fd1991f8e817.png)

After entering daily march 10 2024 and pressing enter, i am on a empty line and i dont know what i am suppose to type next. Could you fix this bug.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: TimothyLKM/ped#5

**Comment by BenjoBurger** [comment]
Sorry for the lack of explanation in the UG, I have rectified this issue.
